# Generated by Django 5.0.6 on 2024-09-02 13:06

import account.manager
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', account.manager.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
