# Generated by Django 5.0.6 on 2024-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
