# Generated by Django 5.0.6 on 2024-09-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_auth_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='auth_token',
            new_name='verf_link',
        ),
    ]
