# Generated by Django 5.0.6 on 2024-09-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.TextField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
