# Generated by Django 5.0.6 on 2024-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_cartitem_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.TextField(default='M'),
            preserve_default=False,
        ),
    ]
