# Generated by Django 5.0.6 on 2024-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_cartitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_img',
            field=models.ImageField(upload_to='cart_prods'),
        ),
    ]
